# .github/workflows/update-reappro.yml
name: Mise à jour quotidienne du CSV de réappro

on:
  schedule:
    # Tous les jours à 02h00
    - cron: '0 2 * * *'

jobs:
  update-reappro:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le dépôt avec persistance du token pour le push
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Télécharger le CSV de réappro (URL corrigée)
      - name: Télécharger le CSV de réappro
        run: |
          curl -fsSL "https://files.karibanbrands.com/documents/SPASSO_REAPPROWEB_SP.csv" \
            -o public/SPASSO_REAPPROWEB_SP.csv

      # 3) Commit & push uniquement si le CSV a changé
      - name: Commit & push si modifié
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add public/SPASSO_REAPPROWEB_SP.csv
          if git diff --cached --quiet; then
            echo "Aucun changement détecté – pas de commit."
          else
            git commit -m "Mise à jour quotidienne du CSV de réappro"
            git push
          fi
